site_name: Enterprise Computing - Stage 6 - NSW
theme:
  name: material
  features: 
    - navigation.tabs
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: deep orange
      accent: teal
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: deep orange
      accent: brown

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - attr_list
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css
extra_javascript:
  - javascripts/katex.js
  - javascripts/feedback.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
plugins:
  - search:
  - glossary:
  - mkdocs_quiz:
extra:
  analytics:
    provider: google
    property: G-YG16K7VJ8G
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/mr-bev/software-engineering-stage6-nsw/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">feedback form</a>.
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognise your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
nav:
  - Home: index.md
  - Interactive Media:
    - Syllabus: interactive_media/index.md
    - Introduction to Interactive Media: interactive_media/introduction_to_interactive_media.md
    - Interactive Media in Enterprises: interactive_media/interactive_media_in_enterprises.md
    - Understanding UX and UI: interactive_media/understanding_ux_and_ui.md
  - Networking Systems:
    - Overview: networking_systems/index.md
  - CyberSecurity:
    - Overview: cybersecurity/index.md
  - Data Science:
    - Overview: data_science/index.md
  - Data Visualisation:
    - Overview: data_visualisation/index.md
  - Intelligent Systems:
    - Overview: intelligent_systems/index.md
  - Enterprise Project:
    - Overview: enterprise_project/index.md
  - Glossary : glossary.md